@echo off
echo Warning, this code is generated by ChatGPT. Running this on your system won't do any harm, but it is just generally bad code.
pause

:: Windows 11 Logo Recreation in Batch
:: Author: AI Coder

:: Set up the console appearance
color 1F  :: Blue background with white text
title Windows 11 Logo Recreation

:: Clear the screen
cls

:: Print the Windows 11 logo as ASCII Art
echo.
echo       ███       ███         ███       ███
echo       ███       ███         ███       ███
echo       ███       ███         ███       ███
echo.
echo       ███       ███         ███       ███
echo       ███       ███         ███       ███
echo       ███       ███         ███       ███
echo.
echo.          Windows 11 (ASCII Recreation)

:: Pause to allow the user to view the artwork
echo.
pause>nul
exit
